doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(DATABASE_URL)%'
                driver: 'pdo_mysql'
            source:
                # configure these for your database server
                url: '%env(DATABASE_URL_SOURCE)%'
                driver: 'pdo_mysql'
            destination:
                # configure these for your database server
                url: '%env(DATABASE_URL_DESTINATION)%'
                driver: 'pdo_mysql'
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity\\'
                        alias: Main
            source:
                connection: source
                mappings:
                    CustomerDetails:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity\UserDetails'
                        alias: UserDetails
            destination:
                connection: destination
                mappings:
                    CustomerDetails:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity\CustomerDetails'
                        alias: CustomerDetails
