migrations_directory: './src/Migrations/destination'
# namespace is arbitrary but should be different from App\Migrations
# as migrations classes should NOT be autoloaded
migrations_namespace: DoctrineMigrations
table_name: migration_versions